# Generated by Django 5.2.6 on 2025-09-10 08:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISIN', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('issue_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField()),
                ('coupon_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BondPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField(default='2025-09-12')),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='bonds.bond')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('price', 'date')},
            },
        ),
    ]
