# Generated by Django 5.2.6 on 2025-09-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
