# Generated by Django 5.2.6 on 2025-09-10 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_bond_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bond',
            old_name='quantity',
            new_name='redemption',
        ),
        migrations.AddField(
            model_name='bond',
            name='coupon_frequency',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bond',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bond',
            name='issue_price',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=10),
        ),
    ]
