# Generated by Django 5.2.6 on 2025-09-12 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_rename_quantity_bond_redemption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='coupon_frequency',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='bondprice',
            name='date',
            field=models.DateField(default='2025-09-16'),
        ),
    ]
